"""ORM table models.

These are the *persistence* representations and are intentionally distinct from
the domain DTO ``app.models.message.Message`` (a Pydantic model used across
layers).  Mapping between the two happens inside the SQL repositories (BE-3),
keeping the rest of the application decoupled from SQLAlchemy.

Schema
------
``users``
    One row per frontend participant, identified by a unique ``username``.
    ``telegram_chat_id`` is NULL until the participant's first Telegram message
    binds a chat to them (the "linking moment").

``messages``
    One row per message, owned by a ``username`` (FK → ``users.username``).
    ``sequence`` is a global, monotonically increasing ordering key.
"""

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.dal.db.base import Base


class UserORM(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    username: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    telegram_chat_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    last_active_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    messages: Mapped[list["MessageORM"]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
    )


class MessageORM(Base):
    __tablename__ = "messages"

    # UUID string generated by the application (see app.helpers.id_helper).
    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    username: Mapped[str] = mapped_column(
        String(255),
        ForeignKey("users.username", ondelete="CASCADE"),
        nullable=False,
    )
    text: Mapped[str] = mapped_column(Text, nullable=False)
    # "incoming" (Telegram → Frontend) or "outgoing" (Frontend → Telegram).
    direction: Mapped[str] = mapped_column(String(16), nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    sequence: Mapped[int] = mapped_column(BigInteger, nullable=False)

    user: Mapped["UserORM"] = relationship(back_populates="messages")

    __table_args__ = (
        Index("ix_messages_username_sequence", "username", "sequence"),
    )
